### ISSUE TITLE
Customize directories to format

### ISSUE THREAD

**Issue by BeastyBlacksmith** [tkf/julia-code-style-suggesters#1]
Would be nice to be able to set the paths, which should be formatted by JuliaFormatter.

**Comment by tkf** [comment]
Hi, thanks for your interest. I created this Action only for making managing my projects easy. There's a secondary goal for documenting how to use various packages and actions together. But, I don't have a throughput ATM for responding to feature requests and maintaining them.

action.yml is actually pretty simple. So, I think it's much easier to just copy it and tweak it in your workflow file.

(I probably should mention this in README)

**Comment by tkf** [comment]
But I'm also happy to help a bit if some people like https://github.com/julia-actions devs want to do something similar.
